-- MySQL Script generated by MySQL Workbench
-- Tue Dec 12 20:12:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imarket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `imarket` ;

-- -----------------------------------------------------
-- Schema imarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imarket` DEFAULT CHARACTER SET utf8 ;
USE `imarket` ;

-- -----------------------------------------------------
-- Table `imarket`.`user_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`user_details` ;

CREATE TABLE IF NOT EXISTS `imarket`.`user_details` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `birth_date` DATETIME NOT NULL,
  `address` VARCHAR(255) NULL,
  `telephone` VARCHAR(45) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imarket`.`user_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`user_state` ;

CREATE TABLE IF NOT EXISTS `imarket`.`user_state` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imarket`.`user_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`user_types` ;

CREATE TABLE IF NOT EXISTS `imarket`.`user_types` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `user_types` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imarket`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`user` ;

CREATE TABLE IF NOT EXISTS `imarket`.`user` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_state_ID` INT UNSIGNED NOT NULL,
  `user_details_ID` INT NOT NULL,
  `user_types_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `imarket`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`category` ;

CREATE TABLE IF NOT EXISTS `imarket`.`category` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imarket`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`products` ;

CREATE TABLE IF NOT EXISTS `imarket`.`products` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `url_imagen` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `category_ID` INT NOT NULL,
  `user_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imarket`.`ranking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`ranking` ;

CREATE TABLE IF NOT EXISTS `imarket`.`ranking` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imarket`.`products_has_ranking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`products_has_ranking` ;

CREATE TABLE IF NOT EXISTS `imarket`.`products_has_ranking` (
  `products_ID` INT NOT NULL,
  `ranking_ID` INT NOT NULL,
  PRIMARY KEY (`products_ID`, `ranking_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imarket`.`pay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`pay` ;

CREATE TABLE IF NOT EXISTS `imarket`.`pay` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(30) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imarket`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imarket`.`transactions` ;

CREATE TABLE IF NOT EXISTS `imarket`.`transactions` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `coments` VARCHAR(50) NULL,
  `ranking_ID` INT NOT NULL,
  `pay_ID` INT NOT NULL,
  `ID_user_sell` INT UNSIGNED NOT NULL,
  `ID_user_buy` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
